name: glycoiqapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  url_launcher: ^6.3.1
  flutter_blue_plus: ^1.35.3
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # flutter_launcher_icons: ^0.14.3

flutter_icons:
  image_path: "assets/icons/icon.png" 
  android: true
  ios: true

flutter_native_splash:
  image: "assets/icons/icon.png" # Your splash image
  branding: "assets/icons/branding.png"
  android: true
  ios: true
  fullscreen: true # Optional
  android_12:
    image: assets/icons/icon.png
    color: "#FFFFFF"
  



flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
